### ISSUE TITLE
Dificuldade na visualização do header - Acesso em mobile

### ISSUE THREAD

**Issue by cnlopes** [nodeschool/belo-horizonte#12]
Pessoal, reparei que ao acessar a [Página do NodeSchool BH](http://nodeschool.io/belo-horizonte/) no celular o título aparece meio desorientado.

![screen shot 2015-05-12 at 22](https://cloud.githubusercontent.com/assets/5844175/7601901/611d2a3e-f8f3-11e4-892b-bf1bebb6ab04.png)

Acho que só diminuir o tamanho da fonte pra esse breakpoint já resolveria.

Colocar o código do site aqui no repositório talvez seria uma boa também.

**Comment by tallesl** [comment]
O código do site fica no branch [gh-pages](https://github.com/nodeschool/belo-horizonte/tree/gh-pages) (né?)

**Comment by cnlopes** [comment]
Verdade @tallesl, passou despercebido... Valeu!
