### ISSUE TITLE
do you have any photos / videos from international-day?

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/belo-horizonte#18]

**Comment by cnlopes** [comment]
Sure
![2015-05-23 12 06 40](https://cloud.githubusercontent.com/assets/5844175/12044850/97303674-ae4d-11e5-8400-45768f12f665.jpg)
![2015-05-23 13 39 12](https://cloud.githubusercontent.com/assets/5844175/12044851/974df5ce-ae4d-11e5-9766-2f3d7fd6a8d3.jpg)

**Comment by iancrowther** [comment]
awsm, ty
