### ISSUE TITLE
Local

### ISSUE THREAD

**Issue by paulohp** [nodeschool/belo-horizonte#2]
Obviamente, precisamos de um local. Já temos algumas possibilidades realmente sólidas sobre isso, mas precisamos ter em mente que o formato de workshop impõe algumas restrições, como mesas, acesso à internet, etc.

**Comment by victorferraz** [comment]
Acho que cada um tem que ter o seu notebook. Não acha?

**Comment by paulohp** [comment]
Fechamos na RC Comunicação que esta gentilmente sendendo espaço, energia e internet! thanks @victorferraz e @erickbelfy! You guys rocks!
