### ISSUE TITLE
Mentores

### ISSUE THREAD

**Issue by paulohp** [nodeschool/belo-horizonte#3]
Há algum javascripter bão que não se importaria de ajudar como mentor durante o workshop? Mencione-os aqui!

**Comment by obetomuniz** [comment]
@erickbelfy @victorferraz @paulohp @wemersonblend

**Comment by wemersonblend** [comment]
Wow, grande honra, pode contar!
@charlesshaefer

**Comment by victorferraz** [comment]
Seria uma honra, mas não tenho tanta XP em node :/

**Comment by paulohp** [comment]
@tallesl se prontificou a ajudar tbm!

Ate agora somos:
@paulohp, @wemersonblend, @victorferraz e @tallesl 

Acho que 5 pra 20 pessoas é legal.

**Comment by victorferraz** [comment]
o @erickbelfy anima também

**Comment by obetomuniz** [comment]
me :+1:

**Comment by paulohp** [comment]
Precisamos fechar os mentores, como serão 14 vagas, acho que 4 mentores ficaria legal. Lembrando que não precisa ser mestre Jedi em Node/IO.js. Só precisa ter boa vontade em ajudar e propagar o conhecimento. Eu to mais que dentro!!!!!!!

Quem topa? @obetomuniz @wemersonblend @tallesl @victorferraz e @erickbelfy ?

**Comment by wemersonblend** [comment]
To dentro!

**Comment by tallesl** [comment]
Eu animo!

Mas não faço questão não, se houver mentores de mais vou como _não mentor_ mesmo :grin:

**Comment by obetomuniz** [comment]
I do it! @paulohp

**Comment by cnlopes** [comment]
Tenho interesse caso ainda estejam precisando

**Comment by tallesl** [comment]
Vixi, reparei só hoje que vocês já tinham criado [o evento](http://eventick.com.br/nodeschool-bh). Esgotou né? :sweat:

**Comment by paulohp** [comment]
Sim, para participantes.
A Lista dos mentores está assim:
- [x] @paulohp
- [x] @obetomuniz 
- [ ] @wemersonblend 
- [ ] @erickbelfy (RC)
- [ ] @victorferraz (RC)

Ainda podendo entrar:
- [ ] @tallesl 
- [ ] @cosmenavarro  

Vou organizar um hangout e mandar email para todos com o que eu penso que seria legal abordar.

Abs.

**Comment by obetomuniz** [comment]
I'm in :)

**Comment by cnlopes** [comment]
beleza!

**Comment by victorferraz** [comment]
Para essa data, fica apertado para mim, pode colocar outra pessoa no meu lugar.
