### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by paulohp** [nodeschool/belo-horizonte#4]
Qual a melhor data pra poder fazer o workshop?

**Comment by obetomuniz** [comment]
@paulohp Depende, seria no final de semana?

**Comment by paulohp** [comment]
Sim, num sabado. O Luri tava falando em 28/2, mas meu voto vai pro inicio de Março, tipo 07/03

**Comment by wemersonblend** [comment]
Tem meu voto aí 07/03.
28/02 tá muito encima!

**Comment by victorferraz** [comment]
Acho uma data curta poderia ser lá para maio

**Comment by tallesl** [comment]
Ficou fechado para 07/03?

_(espero que não, é amanhã :cry:)_

**Comment by paulohp** [comment]
Data fechada em 23/05/2015 de 09h as 17h na RC Comunicação!
