### ISSUE TITLE
Comida e Bebida?

### ISSUE THREAD

**Issue by paulohp** [nodeschool/belo-horizonte#5]
Podemos pensar em algum apoio nesse sentido, seria legal ter um lanche pra fazer networking.

**Comment by victorferraz** [comment]
Acho que também seria. Mas como é pouca gente acho difícil conseguir patrocínio. Eu animo de tirar uma grana do bolso para pagar um lanche, isso geralmente acontece no NodebrBH mesmo.

**Comment by paulohp** [comment]
@victorferraz Eu tambem animo sem problemas! Vamos ver se conseguimos um patrocinio pras camisas e o coffe a gente paga com o dinheiro dos ingressos. É uma boa? @erickbelfy @obetomuniz opinem.

**Comment by obetomuniz** [comment]
cara... acho justo dividir entre todos os presentes sim... super apoio o lance de cobrar pelos comes e bebes :smile:

**Comment by paulohp** [comment]
Ficou definido o valor de R$25,00 para cada pessoa para arcar com o coffee-break e sneaks!
