### ISSUE TITLE
CAMISAAAAS!

### ISSUE THREAD

**Issue by paulohp** [nodeschool/belo-horizonte#6]
Nada mais legal pra deixar um evento marcado que uma bela camiseta. O que acham de procurar parceiros para isso?

**Comment by victorferraz** [comment]
Eu acho ótimo, você saberia ter interessados nisso?

**Comment by paulohp** [comment]
Acho que a TopTal, posso mandar um email pro Twitter tbm, stroogloop. Vamos vendo.

**Comment by obetomuniz** [comment]
Boa @paulohp ...

**Comment by paulohp** [comment]
Vamos ter uma surpresinha pra galera no dia do evento! Aguardem!
