### ISSUE TITLE
Limite de pessoas e plataforma de ingresso.

### ISSUE THREAD

**Issue by paulohp** [nodeschool/belo-horizonte#7]
Acho que 20 pessoas é um bom numero. E podemos usar o eventick como plataforma de ingresso.

**Comment by obetomuniz** [comment]
@paulohp Fecha a conta e passa a régua!

**Comment by paulohp** [comment]
haha @obetomuniz claro! Só fechar a data e já crio o evento no eventick.

**Comment by tallesl** [comment]
Comentei com meus colegas de trabalho sobre o nodeschool e alguns interessaram. Será que tem lugar pra todo mundo?

Colocando-os na conversa:

@arthur-fernandes
@brumano
@cristianofran
@diegovinicius
@geldoronie
@junioalbino
@marck010
@mirandajeff
@paulodamasceno
@Progmaster13
@tuliopimenta
@valteirjr

A maioria (acho que todos) não tem experiência com Node.js, são praticamente todos desenvolvedores .NET.

**Comment by Progmaster13** [comment]
Opa, eu também Talles =)

**Comment by paulohp** [comment]
Vamos fechar em 14 lugares. Em breve vamos disponibilizar a plataforma para adquirir os ingressos. Vamos optar por usar Eventick por ser uma plataforma com expertise nesse tipo de evento.

Lugares: 14.
Plataforma: Eventick
