### ISSUE TITLE
Continua de pé?

### ISSUE THREAD

**Issue by tallesl** [nodeschool/belo-horizonte#8]
Tenho interesse em participar (se quiser posso até mentorar, não sou nenhum _ninja_ mas [tenho meia dúzia de pacotes no npm](https://www.npmjs.com/~talles)).

Já fecharam local, quantidade de pessoas e coisas do tipo? O evento continua de pé? Pergunto pois as issues estão _meio mortas_...

**Comment by paulohp** [comment]
@tallesl que otimo cara! ta de pe sim. Temos o Local sim, vai ser na RC Comunicação no final de março ou inicio de abril, estou vendo a disponibilidade com o pessoal da RC. Pode partcipar das outras issues que estao ai, vamos fazer isso acontecer.

**Comment by tallesl** [comment]
Que bom que segue _de pé_ ;)

Divulguei a idéia para o pessoal da minha empresa e acho que mais gente daqui se interessou além de mim...

Bom, passarei a comentar nas issues apropriadas de cada assunto. Valeu!
